import { createHash } from "node:crypto";
import { canonicalJsonDigest, manifestAggregateDigest } from "./canonicalManifest.js";
import type { CompilationTargetV1 } from "./contracts.js";

export interface ArtifactContractV1 { readonly schemaVersion: "artifact-contract-v1"; readonly target: CompilationTargetV1; readonly root: "dist" | "build/web"; readonly requiredEntrypoints: readonly string[]; readonly extensionMediaTypes: readonly { readonly extension: string; readonly mediaType: string }[]; readonly sourceMapsAllowed: false; readonly executableBitsAllowed: false; readonly allowedModes: readonly ["0444", "0644"]; readonly contractDigest: string; }
const common = [[".avif","image/avif"],[".css","text/css"],[".html","text/html"],[".ico","image/x-icon"],[".jpeg","image/jpeg"],[".jpg","image/jpeg"],[".js","text/javascript"],[".json","application/json"],[".png","image/png"],[".svg","image/svg+xml"],[".txt","text/plain"],[".webp","image/webp"],[".woff","font/woff"],[".woff2","font/woff2"]] as const;
const extras = { astro_web: [[".mjs","text/javascript"],[".webmanifest","application/manifest+json"],[".xml","application/xml"]], flutter_web: [[".bin","application/octet-stream"],[".frag","application/octet-stream"],[".ttf","font/ttf"],[".wasm","application/wasm"]] } as const;
export function artifactContract(target: CompilationTargetV1): ArtifactContractV1 {
  const extensionMediaTypes = [...common, ...extras[target]].map(([extension, mediaType]) => ({ extension, mediaType })).sort((a,b) => a.extension < b.extension ? -1 : 1);
  const core = { schemaVersion: "artifact-contract-v1" as const, target, root: target === "astro_web" ? "dist" as const : "build/web" as const, requiredEntrypoints: target === "astro_web" ? ["index.html"] : ["flutter.js","flutter_bootstrap.js","index.html","manifest.json","version.json"], extensionMediaTypes, sourceMapsAllowed: false as const, executableBitsAllowed: false as const, allowedModes: ["0444","0644"] as const };
  return Object.freeze({ ...core, requiredEntrypoints: Object.freeze(core.requiredEntrypoints), extensionMediaTypes: Object.freeze(extensionMediaTypes.map((item) => Object.freeze({ ...item }))), contractDigest: canonicalJsonDigest(core) });
}
export function validateArtifactContract(value:unknown):ArtifactContractV1 {
  if(value===null||typeof value!=="object"||Array.isArray(value))throw new Error("Artifact contract is invalid.");
  const runtime=value as Record<string,unknown>,contract=value as ArtifactContractV1, keys=["schemaVersion","target","root","requiredEntrypoints","extensionMediaTypes","sourceMapsAllowed","executableBitsAllowed","allowedModes","contractDigest"], actual=Object.keys(value);
  if(actual.length!==keys.length||keys.some((key,index)=>actual[index]!==key)||runtime["schemaVersion"]!=="artifact-contract-v1"||(runtime["target"]!=="astro_web"&&runtime["target"]!=="flutter_web"))throw new Error("Artifact contract is invalid.");
  const expected=artifactContract(contract.target);
  if(JSON.stringify(contract)!==JSON.stringify(expected))throw new Error("Artifact contract is invalid.");
  return expected;
}
export interface ArtifactEntryV1 { readonly path: string; readonly mediaType: string; readonly mode: "0444" | "0644"; readonly sizeBytes: number; readonly fileDigest: string; }
export interface ArtifactFileObservationV1 {readonly identity:string;readonly kind:string;readonly linkCount:number;readonly mode:string;readonly sizeBytes:number;readonly fileDigest:string;}
export function verifyArtifactByteStream(entry:ArtifactEntryV1,before:ArtifactFileObservationV1,chunks:readonly Uint8Array[],after:ArtifactFileObservationV1):string {if(before.identity===""||before.kind!=="regular"||after.kind!=="regular"||before.linkCount!==1||after.linkCount!==1||before.identity!==after.identity||before.mode!==entry.mode||after.mode!==entry.mode||before.sizeBytes!==entry.sizeBytes||after.sizeBytes!==entry.sizeBytes||before.fileDigest!==entry.fileDigest||after.fileDigest!==entry.fileDigest)throw new Error("Artifact changed.");const hash=createHash("sha256");let bytes=0;for(const chunk of chunks){bytes+=chunk.byteLength;if(bytes>entry.sizeBytes)throw new Error("Artifact changed.");hash.update(chunk);}const streamed=hash.digest("hex");if(bytes!==entry.sizeBytes||streamed!==entry.fileDigest)throw new Error("Artifact changed.");return streamed;}
export interface CompilationArtifactManifestV1 { readonly schemaVersion: "compilation-artifact-manifest-v1"; readonly jobId: string; readonly tenantId: string; readonly projectId: string; readonly target: CompilationTargetV1; readonly sourceAggregateDigest: string; readonly toolchainDigest: string; readonly imageDigest: string; readonly artifactContractDigest: string; readonly entries: readonly ArtifactEntryV1[]; readonly fileCount: number; readonly totalBytes: number; readonly artifactAggregateDigest: string; readonly createdAt: string; }
export function validateArtifactManifest(value: CompilationArtifactManifestV1, contract: ArtifactContractV1): CompilationArtifactManifestV1 {
  const keys=["schemaVersion","jobId","tenantId","projectId","target","sourceAggregateDigest","toolchainDigest","imageDigest","artifactContractDigest","entries","fileCount","totalBytes","artifactAggregateDigest","createdAt"];
  if(Object.keys(value).length!==keys.length||keys.some((key,index)=>Object.keys(value).at(index)!==key)||(value as {readonly schemaVersion:unknown}).schemaVersion!=="compilation-artifact-manifest-v1"||![value.jobId,value.tenantId,value.projectId].every((item)=>/^[a-z0-9_-]{22,128}$/.test(item))||![value.sourceAggregateDigest,value.toolchainDigest,value.imageDigest,value.artifactContractDigest,value.artifactAggregateDigest].every((item)=>/^[a-f0-9]{64}$/.test(item))||!/^[0-9]{4}-[0-9]{2}-[0-9]{2}T[0-9]{2}:[0-9]{2}:[0-9]{2}\.[0-9]{3}Z$/.test(value.createdAt)||value.target !== contract.target || value.artifactContractDigest !== contract.contractDigest || value.fileCount !== value.entries.length || value.fileCount > 4096) throw new Error("Artifact is invalid.");
  const media = new Map(contract.extensionMediaTypes.map((item) => [item.extension, item.mediaType])); let total = 0; const paths = new Set(value.entries.map((entry) => entry.path));
  for (const required of contract.requiredEntrypoints) if (!paths.has(required)) throw new Error("Artifact required entrypoint is missing.");
  for (const entry of value.entries) {if(Object.keys(entry).join(",")!=="path,mediaType,mode,sizeBytes,fileDigest"||!/^[a-f0-9]{64}$/.test(entry.fileDigest)||!Number.isSafeInteger(entry.sizeBytes)||entry.sizeBytes<0)throw new Error("Artifact is invalid.");const extension=/(\.[^.]+)$/u.exec(entry.path)?.[1]??"";if(extension===".map"||media.get(extension)!==entry.mediaType||!contract.allowedModes.includes(entry.mode)||entry.sizeBytes>16_777_216||((extension===".bin"||extension===".frag")&&!entry.path.startsWith("assets/")))throw new Error("Artifact is invalid.");total+=entry.sizeBytes; }
  if (total !== value.totalBytes || total > 134_217_728) throw new Error("Artifact limit exceeded.");
  if (manifestAggregateDigest(value.entries) !== value.artifactAggregateDigest) throw new Error("Artifact digest is invalid."); return Object.freeze({ ...value, entries: Object.freeze(value.entries.map((entry) => Object.freeze({ ...entry }))) });
}
