import { canonicalJsonDigest } from "./canonicalManifest.js";

export type CompilationTargetV1 = "astro_web" | "flutter_web";
export type CompilationPlanNameV1 = "astro_web_v1" | "flutter_web_v1";
export type CompilationJobState = "planned" | "admitted" | "running" | "retrieving" | "verified" | "failed" | "quarantined" | "released" | "revoked";
export type CompilationClosedReason = "disabled" | "unsupportedTarget" | "projectUnproved" | "routeStale" | "sourceChanged" | "sourceInvalid" | "sourceLimitExceeded" | "capabilityInvalid" | "capabilityExpired" | "capabilityReplayed" | "planInvalid" | "workerUnproved" | "workerIncompatible" | "oidcInvalid" | "budgetUnavailable" | "budgetExceeded" | "providerUnavailable" | "executionFailed" | "executionTimedOut" | "logLimitExceeded" | "artifactInvalid" | "artifactLimitExceeded" | "artifactUnproved" | "cleanupUncertain" | "revoked";
export const COMPILATION_CLOSED_REASONS = Object.freeze(["disabled","unsupportedTarget","projectUnproved","routeStale","sourceChanged","sourceInvalid","sourceLimitExceeded","capabilityInvalid","capabilityExpired","capabilityReplayed","planInvalid","workerUnproved","workerIncompatible","oidcInvalid","budgetUnavailable","budgetExceeded","providerUnavailable","executionFailed","executionTimedOut","logLimitExceeded","artifactInvalid","artifactLimitExceeded","artifactUnproved","cleanupUncertain","revoked"] as const);

const transitions: Readonly<Record<CompilationJobState, readonly CompilationJobState[]>> = Object.freeze({ planned: ["admitted", "failed", "quarantined", "revoked"], admitted: ["running", "failed", "quarantined", "revoked"], running: ["retrieving", "failed", "quarantined", "revoked"], retrieving: ["verified", "failed", "quarantined", "revoked"], verified: ["released", "quarantined", "revoked"], failed: ["quarantined", "revoked"], quarantined: ["revoked"], released: ["revoked"], revoked: [] });
export function transitionCompilationJob(from: CompilationJobState, to: CompilationJobState): CompilationJobState { if (!transitions[from].includes(to)) throw new Error("Compilation job transition is invalid."); return to; }

export interface CompilationPlanV1 { readonly schemaVersion: "compilation-plan-v1"; readonly planId: string; readonly jobId: string; readonly plan: CompilationPlanNameV1; readonly workingDirectory: "/workspace/source"; readonly outputRoot: "dist" | "build/web"; readonly durationMsMax: 600000; readonly stdoutBytesMax: 1048576; readonly stderrBytesMax: 1048576; readonly planDigest: string; }
export function compilationPlan(plan: CompilationPlanNameV1, planId: string, jobId: string): CompilationPlanV1 {
  if (!(new Set<string>(["astro_web_v1", "flutter_web_v1"])).has(plan) || !opaque.test(planId) || !opaque.test(jobId)) throw new Error("Compilation plan is invalid.");
  const core = { schemaVersion: "compilation-plan-v1" as const, planId, jobId, plan, workingDirectory: "/workspace/source" as const, outputRoot: plan === "astro_web_v1" ? "dist" as const : "build/web" as const, durationMsMax: 600000 as const, stdoutBytesMax: 1048576 as const, stderrBytesMax: 1048576 as const };
  return Object.freeze({ ...core, planDigest: canonicalJsonDigest(core) });
}
export function compilationPlanCommands(plan:CompilationPlanNameV1):readonly (readonly string[])[] {const commands=plan==="astro_web_v1"?[["pnpm","install","--offline","--frozen-lockfile","--ignore-scripts"],["pnpm","exec","astro","check"],["pnpm","exec","astro","build"]]:[["flutter","pub","get","--offline","--enforce-lockfile"],["flutter","build","web","--release","--no-pub"]];return Object.freeze(commands.map((argv)=>Object.freeze(argv)));}
export function validateCompilationPlan(value:unknown):CompilationPlanV1 {if(!record(value)){throw new Error("Compilation plan invalid.");}const keys=["schemaVersion","planId","jobId","plan","workingDirectory","outputRoot","durationMsMax","stdoutBytesMax","stderrBytesMax","planDigest"];if(Object.keys(value).length!==keys.length||keys.some((key,index)=>Object.keys(value).at(index)!==key))throw new Error("Compilation plan invalid.");const plan=value as unknown as CompilationPlanV1;const expected=compilationPlan(plan.plan,plan.planId,plan.jobId);if(JSON.stringify(plan)!==JSON.stringify(expected))throw new Error("Compilation plan invalid.");return Object.freeze({...plan});}

const jobKeys = ["schemaVersion","jobId","tenantId","projectId","requestedTarget","sourceRevision","sourceManifestDigest","sourceAggregateDigest","routeRequirementDigest","executionClass","toolchainProfile","toolchainDigest","imageDigest","policyDigest","artifactContractDigest","budgetDigest","admissionCapabilityDigest","sourceIngressCapabilityDigest","executionCapabilityDigest","artifactVerificationLeaseDigest","artifactEgressCapabilityDigest","state","reason","createdAt","updatedAt","expiresAt"];
export function validateCompilationJob(value: unknown): Readonly<Record<string, unknown>> {
  if (!record(value) || !exactKeys(value, jobKeys)) throw new Error("Compilation job is invalid.");
  const target=value["requestedTarget"], execution=value["executionClass"], profile=value["toolchainProfile"], state=value["state"], reason=value["reason"];
  const phaseKeys=["admissionCapabilityDigest","sourceIngressCapabilityDigest","executionCapabilityDigest","artifactVerificationLeaseDigest","artifactEgressCapabilityDigest"];
  if(value["schemaVersion"]!=="compilation-job-v1"||![value["jobId"],value["tenantId"],value["projectId"]].every(isOpaque)||!isTarget(target)||typeof value["sourceRevision"]!=="string"||!/^[\x20-\x7e]{1,128}$/.test(value["sourceRevision"])||!["sourceManifestDigest","sourceAggregateDigest","routeRequirementDigest","toolchainDigest","imageDigest","policyDigest","artifactContractDigest","budgetDigest"].every((key)=>isDigest(value[key]))||!phaseKeys.every((key)=>value[key]===null||isDigest(value[key]))||!isState(state)||!(reason===null||isReason(reason))||!isTimestamp(value["createdAt"])||!isTimestamp(value["updatedAt"])||!isTimestamp(value["expiresAt"])||Date.parse(value["createdAt"])>Date.parse(value["updatedAt"])||Date.parse(value["updatedAt"])>Date.parse(value["expiresAt"]))throw new Error("Compilation job is invalid.");
  if((target==="astro_web"&&(execution!=="linux_node"||profile!=="astro_static"))||(target==="flutter_web"&&(execution!=="linux_flutter"||profile!=="flutter_web")))throw new Error("Compilation job is invalid.");
  const phaseDigests=phaseKeys.map((key)=>value[key]).filter((item):item is string=>typeof item==="string");if(new Set(phaseDigests).size!==phaseDigests.length)throw new Error("Compilation job is invalid.");
  if((["failed","quarantined","revoked"] as readonly unknown[]).includes(state) !== (reason!==null))throw new Error("Compilation job is invalid.");
  return Object.freeze({...value});
}
function record(value: unknown): value is Record<string, unknown> { return value !== null && typeof value === "object" && !Array.isArray(value); }

export type PhaseGrantState = "issued" | "consumed" | "revoked";
interface CapabilityBase { readonly capabilityId:string;readonly capabilityDigest:string;readonly jobId:string;readonly tenantId:string;readonly projectId:string;readonly target:CompilationTargetV1;readonly routeRequirementDigest:string;readonly issuedAt:string;readonly expiresAt:string;readonly state:PhaseGrantState; }
export interface AdmissionCapabilityV1 extends CapabilityBase {readonly schemaVersion:"admission-capability-v1";readonly budgetDigest:string;readonly phase:"admission";}
export interface SourceIngressCapabilityV1 extends CapabilityBase {readonly schemaVersion:"source-ingress-capability-v1";readonly sourceManifestDigest:string;readonly sourceAggregateDigest:string;readonly workerEvidenceDigest:string;readonly phase:"source_ingress";}
export interface ExecutionCapabilityV1 extends CapabilityBase {readonly schemaVersion:"execution-capability-v1";readonly sourceAggregateDigest:string;readonly workerEvidenceDigest:string;readonly planDigest:string;readonly artifactContractDigest:string;readonly phase:"execution";}
export interface ArtifactEgressCapabilityV1 extends CapabilityBase {readonly schemaVersion:"artifact-egress-capability-v1";readonly artifactManifestDigest:string;readonly artifactAggregateDigest:string;readonly privateBrokerObjectDigest:string;readonly cleanupEvidenceDigest:string;readonly phase:"artifact_egress";}
export type ExactCapabilityV1=AdmissionCapabilityV1|SourceIngressCapabilityV1|ExecutionCapabilityV1|ArtifactEgressCapabilityV1;
const opaque=/^[a-z0-9_-]{22,128}$/; const digest=/^[a-f0-9]{64}$/;
const capabilityKeys:Readonly<Record<ExactCapabilityV1["phase"],readonly string[]>>={admission:["schemaVersion","capabilityId","capabilityDigest","jobId","tenantId","projectId","target","routeRequirementDigest","budgetDigest","phase","issuedAt","expiresAt","state"],source_ingress:["schemaVersion","capabilityId","capabilityDigest","jobId","tenantId","projectId","target","routeRequirementDigest","sourceManifestDigest","sourceAggregateDigest","workerEvidenceDigest","phase","issuedAt","expiresAt","state"],execution:["schemaVersion","capabilityId","capabilityDigest","jobId","tenantId","projectId","target","routeRequirementDigest","sourceAggregateDigest","workerEvidenceDigest","planDigest","artifactContractDigest","phase","issuedAt","expiresAt","state"],artifact_egress:["schemaVersion","capabilityId","capabilityDigest","jobId","tenantId","projectId","target","routeRequirementDigest","artifactManifestDigest","artifactAggregateDigest","privateBrokerObjectDigest","cleanupEvidenceDigest","phase","issuedAt","expiresAt","state"]};
export function capabilityDigest(value:ExactCapabilityV1):string {const projection:Record<string,unknown>={};for(const key of capabilityKeys[value.phase])if(key!=="capabilityDigest"&&key!=="state")projection[key]=(value as unknown as Record<string,unknown>)[key];return canonicalJsonDigest(projection);}
export function validateCapability(value:unknown):ExactCapabilityV1 {
  if(!record(value)||!["admission","source_ingress","execution","artifact_egress"].includes(String(value["phase"])))throw new Error("Capability invalid.");
  const phase=value["phase"] as ExactCapabilityV1["phase"], keys=capabilityKeys[phase], issued=Date.parse(String(value["issuedAt"])), expires=Date.parse(String(value["expiresAt"]));
  const schemas={admission:"admission-capability-v1",source_ingress:"source-ingress-capability-v1",execution:"execution-capability-v1",artifact_egress:"artifact-egress-capability-v1"} as const;
  if(!exactKeys(value,keys)||value["schemaVersion"]!==schemas[phase]||![value["capabilityId"],value["jobId"],value["tenantId"],value["projectId"]].every(isOpaque)||!isTarget(value["target"])||!isDigest(value["routeRequirementDigest"])||!["issued","consumed","revoked"].includes(String(value["state"]))||!isTimestamp(value["issuedAt"])||!isTimestamp(value["expiresAt"])||!Number.isFinite(issued)||!Number.isFinite(expires)||expires<=issued||expires-issued>300000)throw new Error("Capability invalid.");
  const phaseDigests:Readonly<Record<ExactCapabilityV1["phase"],readonly string[]>>={admission:["budgetDigest"],source_ingress:["sourceManifestDigest","sourceAggregateDigest","workerEvidenceDigest"],execution:["sourceAggregateDigest","workerEvidenceDigest","planDigest","artifactContractDigest"],artifact_egress:["artifactManifestDigest","artifactAggregateDigest","privateBrokerObjectDigest","cleanupEvidenceDigest"]};
  if(!phaseDigests[phase].every((key)=>isDigest(value[key]))||value["capabilityDigest"]!==capabilityDigest(value as unknown as ExactCapabilityV1))throw new Error("Capability invalid.");
  return Object.freeze({...value}) as unknown as ExactCapabilityV1;
}
export class ExactCapabilityStore {
  readonly #grants=new Map<string,ExactCapabilityV1>();
  issueAdmission(input:Omit<AdmissionCapabilityV1,"capabilityDigest"|"state">):AdmissionCapabilityV1 {const draft={schemaVersion:input.schemaVersion,capabilityId:input.capabilityId,capabilityDigest:"",jobId:input.jobId,tenantId:input.tenantId,projectId:input.projectId,target:input.target,routeRequirementDigest:input.routeRequirementDigest,budgetDigest:input.budgetDigest,phase:input.phase,issuedAt:input.issuedAt,expiresAt:input.expiresAt,state:"issued" as const};return this.#store({...draft,capabilityDigest:capabilityDigest(draft)});}
  issueSourceIngress(input:Omit<SourceIngressCapabilityV1,"capabilityDigest"|"state">):SourceIngressCapabilityV1 {return this.#issueOrdered(input,capabilityKeys.source_ingress) as SourceIngressCapabilityV1;}
  issueExecution(input:Omit<ExecutionCapabilityV1,"capabilityDigest"|"state">):ExecutionCapabilityV1 {return this.#issueOrdered(input,capabilityKeys.execution) as ExecutionCapabilityV1;}
  issueArtifactEgress(input:Omit<ArtifactEgressCapabilityV1,"capabilityDigest"|"state">):ArtifactEgressCapabilityV1 {return this.#issueOrdered(input,capabilityKeys.artifact_egress) as ArtifactEgressCapabilityV1;}
  consume(id:string,now:Date,scope:CapabilityConsumptionScope):ExactCapabilityV1 {if(!(now instanceof Date)||!Number.isFinite(now.getTime()))throw new Error("Capability invalid.");const current=this.#grants.get(id);if(current?.state!=="issued")throw new Error("Capability replayed.");if(Date.parse(current.expiresAt)<now.getTime()){this.revoke(id);throw new Error("Capability expired.");}if(!capabilityScopeMatches(current,scope)){this.revoke(id);throw new Error("Capability invalid.");}const next=Object.freeze({...current,state:"consumed" as const});this.#grants.set(id,next);return next;}
  revoke(id:string):ExactCapabilityV1 {const current=this.#grants.get(id);if(current===undefined)throw new Error("Capability invalid.");if(current.state==="revoked")return current;const next=Object.freeze({...current,state:"revoked" as const});this.#grants.set(id,next);return next;}
  #issueOrdered(input:object,keys:readonly string[]):ExactCapabilityV1 {const source=input as Record<string,unknown>;const draft:Record<string,unknown>={};for(const key of keys)draft[key]=key==="capabilityDigest"?"":key==="state"?"issued":source[key];return this.#store({...draft,capabilityDigest:capabilityDigest(draft as unknown as ExactCapabilityV1)} as unknown as ExactCapabilityV1);}
  #store<T extends ExactCapabilityV1>(value:T):T {const grant=validateCapability(value) as T;if(this.#grants.has(grant.capabilityId))throw new Error("Capability replayed.");this.#grants.set(grant.capabilityId,grant);return grant;}
}
export interface CapabilityConsumptionScope {readonly jobId:string;readonly tenantId:string;readonly projectId:string;readonly target:CompilationTargetV1;readonly phase:ExactCapabilityV1["phase"];readonly routeRequirementDigest:string;readonly budgetDigest?:string;readonly sourceManifestDigest?:string;readonly sourceAggregateDigest?:string;readonly workerEvidenceDigest?:string;readonly planDigest?:string;readonly artifactContractDigest?:string;readonly artifactManifestDigest?:string;readonly artifactAggregateDigest?:string;readonly privateBrokerObjectDigest?:string;readonly cleanupEvidenceDigest?:string;}
function capabilityScopeMatches(value:ExactCapabilityV1,scope:CapabilityConsumptionScope):boolean {if(value.jobId!==scope.jobId||value.tenantId!==scope.tenantId||value.projectId!==scope.projectId||value.target!==scope.target||value.phase!==scope.phase||value.routeRequirementDigest!==scope.routeRequirementDigest)return false;switch(value.phase){case"admission":return value.budgetDigest===scope.budgetDigest;case"source_ingress":return value.sourceManifestDigest===scope.sourceManifestDigest&&value.sourceAggregateDigest===scope.sourceAggregateDigest&&value.workerEvidenceDigest===scope.workerEvidenceDigest;case"execution":return value.sourceAggregateDigest===scope.sourceAggregateDigest&&value.workerEvidenceDigest===scope.workerEvidenceDigest&&value.planDigest===scope.planDigest&&value.artifactContractDigest===scope.artifactContractDigest;case"artifact_egress":return value.artifactManifestDigest===scope.artifactManifestDigest&&value.artifactAggregateDigest===scope.artifactAggregateDigest&&value.privateBrokerObjectDigest===scope.privateBrokerObjectDigest&&value.cleanupEvidenceDigest===scope.cleanupEvidenceDigest;}}

export class ArtifactVerificationLeaseV1 {
  readonly schemaVersion="artifact-verification-lease-v1"; #state:PhaseGrantState="issued";
  constructor(readonly leaseId:string,readonly leaseDigest:string,readonly jobId:string,readonly tenantId:string,readonly projectId:string,readonly target:CompilationTargetV1,readonly routeRequirementDigest:string,readonly artifactContractDigest:string,readonly providerResourceIdDigest:string,readonly workerEvidenceDigest:string,readonly issuedAt:string,readonly expiresAt:string) { const issued=Date.parse(issuedAt),expires=Date.parse(expiresAt);if(!opaque.test(leaseId)||![leaseDigest,routeRequirementDigest,artifactContractDigest,providerResourceIdDigest,workerEvidenceDigest].every((v)=>digest.test(v))||!isTimestamp(issuedAt)||!isTimestamp(expiresAt)||expires<=issued||expires-issued>300000) throw new Error("Lease invalid."); Object.preventExtensions(this); }
  consume(now:Date):void { if(!(now instanceof Date)||!Number.isFinite(now.getTime()))throw new Error("Lease invalid.");if(this.#state!=="issued"||Date.parse(this.expiresAt)<now.getTime()) { this.#state="revoked"; throw new Error("Lease invalid."); } this.#state="consumed"; }
  revoke():void { this.#state="revoked"; }
  get state():PhaseGrantState{return this.#state;}
  toJSON():never { throw new Error("Verification lease is non-serializable."); }
  toString():string { return "[ArtifactVerificationLease]"; }
}
export function createArtifactVerificationLease(input:{leaseId:string;jobId:string;tenantId:string;projectId:string;target:CompilationTargetV1;routeRequirementDigest:string;artifactContractDigest:string;providerResourceIdDigest:string;workerEvidenceDigest:string;issuedAt:string;expiresAt:string}):ArtifactVerificationLeaseV1 {const projection={schemaVersion:"artifact-verification-lease-v1",leaseId:input.leaseId,jobId:input.jobId,tenantId:input.tenantId,projectId:input.projectId,target:input.target,routeRequirementDigest:input.routeRequirementDigest,artifactContractDigest:input.artifactContractDigest,providerResourceIdDigest:input.providerResourceIdDigest,workerEvidenceDigest:input.workerEvidenceDigest,phase:"artifact_verification",issuedAt:input.issuedAt,expiresAt:input.expiresAt};return new ArtifactVerificationLeaseV1(input.leaseId,canonicalJsonDigest(projection),input.jobId,input.tenantId,input.projectId,input.target,input.routeRequirementDigest,input.artifactContractDigest,input.providerResourceIdDigest,input.workerEvidenceDigest,input.issuedAt,input.expiresAt);}

const resultKeys=["schemaVersion","jobId","state","reason","sourceAggregateDigest","artifactManifestDigest","artifactAggregateDigest","workerEvidenceDigest","receiptDigest","stdoutDigest","stderrDigest","startedAt","finishedAt","resultDigest"];
export function validateCompilationResult(value:unknown):Readonly<Record<string,unknown>> { if(!record(value)||!exactKeys(value,resultKeys)||value["schemaVersion"]!=="compilation-result-v1"||!isOpaque(value["jobId"])||!isDigest(value["sourceAggregateDigest"])||!isTimestamp(value["finishedAt"])||!(value["startedAt"]===null||isTimestamp(value["startedAt"]))||value["startedAt"]!==null&&Date.parse(value["startedAt"])>Date.parse(value["finishedAt"])) throw new Error("Compilation result invalid."); const state=value["state"],reason=value["reason"],nullableDigests=["artifactManifestDigest","artifactAggregateDigest","workerEvidenceDigest","receiptDigest","stdoutDigest","stderrDigest"]; if(typeof state!=="string"||!["verified","failed","quarantined","released","revoked"].includes(state)||!nullableDigests.every((key)=>value[key]===null||isDigest(value[key]))||!resultEvidenceValid(state,value)||((state==="verified"||state==="released")?reason!==null:!isReason(reason))) throw new Error("Compilation result invalid."); const expected=canonicalJsonDigest(Object.fromEntries(Object.entries(value).filter(([key])=>key!=="resultDigest"))); if(value["resultDigest"]!==expected) throw new Error("Compilation result digest invalid."); return Object.freeze({...value}); }
function resultEvidenceValid(state:string,value:Record<string,unknown>):boolean {const trio=[value["artifactManifestDigest"],value["artifactAggregateDigest"],value["workerEvidenceDigest"]],present=trio.every(isDigest),absent=trio.every((item)=>item===null);if(state==="verified"||state==="released")return present;if(state==="quarantined")return present||absent;return absent;}

function exactKeys(value:Record<string,unknown>,keys:readonly string[]):boolean {const actual=Object.keys(value);return actual.length===keys.length&&keys.every((key,index)=>actual[index]===key);}
function isOpaque(value:unknown):value is string{return typeof value==="string"&&opaque.test(value);}
function isDigest(value:unknown):value is string{return typeof value==="string"&&digest.test(value);}
function isTarget(value:unknown):value is CompilationTargetV1{return value==="astro_web"||value==="flutter_web";}
function isState(value:unknown):value is CompilationJobState{return typeof value==="string"&&Object.hasOwn(transitions,value);}
function isReason(value:unknown):value is CompilationClosedReason{return typeof value==="string"&&COMPILATION_CLOSED_REASONS.includes(value as CompilationClosedReason);}
function isTimestamp(value:unknown):value is string{return typeof value==="string"&&/^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}\.\d{3}Z$/.test(value)&&Number.isFinite(Date.parse(value));}
