import { createHash } from "node:crypto";
import { manifestAggregateDigest } from "./canonicalManifest.js";
import type { CompilationTargetV1 } from "./contracts.js";

export interface SourceEntryV1 { readonly path: string; readonly kind: "ordinary" | "asset"; readonly sizeBytes: number; readonly fileDigest: string; }
export interface CompilationSourceManifestV1 { readonly schemaVersion: "compilation-source-manifest-v1"; readonly jobId: string; readonly tenantId: string; readonly projectId: string; readonly target: CompilationTargetV1; readonly sourceRevision: string; readonly entries: readonly SourceEntryV1[]; readonly fileCount: number; readonly totalBytes: number; readonly sourceAggregateDigest: string; readonly createdAt: string; }
export interface SourceFileObservationV1 {readonly identity:string;readonly kind:string;readonly linkCount:number;readonly mode:string;readonly sizeBytes:number;readonly fileDigest:string;}
export function verifyIndividuallyStreamedSource(entry:SourceEntryV1,before:SourceFileObservationV1,chunks:readonly Uint8Array[],after:SourceFileObservationV1):string {if(before.identity===""||before.kind!=="regular"||after.kind!=="regular"||before.linkCount!==1||after.linkCount!==1||before.identity!==after.identity||before.mode!==after.mode||before.sizeBytes!==entry.sizeBytes||after.sizeBytes!==entry.sizeBytes||before.fileDigest!==entry.fileDigest||after.fileDigest!==entry.fileDigest)throw new Error("Source changed.");const hash=createHash("sha256");let bytes=0;for(const chunk of chunks){bytes+=chunk.byteLength;if(bytes>entry.sizeBytes)throw new Error("Source changed.");hash.update(chunk);}const streamed=hash.digest("hex");if(bytes!==entry.sizeBytes||streamed!==entry.fileDigest)throw new Error("Source changed.");return streamed;}
export function validateSourceManifest(value: CompilationSourceManifestV1): CompilationSourceManifestV1 {
  const keys=["schemaVersion","jobId","tenantId","projectId","target","sourceRevision","entries","fileCount","totalBytes","sourceAggregateDigest","createdAt"];
  if(Object.keys(value).length!==keys.length||keys.some((key,index)=>Object.keys(value).at(index)!==key)||(value as { readonly schemaVersion: unknown }).schemaVersion !== "compilation-source-manifest-v1"||!id(value.jobId)||!id(value.tenantId)||!id(value.projectId)||!/^(?:astro_web|flutter_web)$/.test(value.target)||!/^[\x20-\x7e]{1,128}$/.test(value.sourceRevision)||!timestamp(value.createdAt)||value.fileCount !== value.entries.length || value.fileCount > 4096) throw new Error("Source manifest is invalid.");
  let total = 0;
  for (const entry of value.entries) {if(Object.keys(entry).join(",")!=="path,kind,sizeBytes,fileDigest"||!allowed(value.target,entry.path))throw new Error("Source manifest is invalid.");const asset=(value.target==="astro_web"?entry.path.startsWith("public/"):entry.path.startsWith("web/"));if((entry.kind==="asset")!==asset)throw new Error("Source manifest is invalid.");const maximum=asset?16_777_216:2_097_152;if(!Number.isSafeInteger(entry.sizeBytes)||entry.sizeBytes<0||entry.sizeBytes>maximum)throw new Error("Source limit exceeded.");total += entry.sizeBytes; }
  if (total !== value.totalBytes || total > 67_108_864) throw new Error("Source limit exceeded.");
  if (manifestAggregateDigest(value.entries) !== value.sourceAggregateDigest) throw new Error("Source digest is invalid.");
  return Object.freeze({ ...value, entries: Object.freeze(value.entries.map((entry) => Object.freeze({ ...entry }))) });
}
function allowed(target:CompilationTargetV1,path:string):boolean {if(target==="astro_web")return ["package.json","pnpm-lock.yaml","pnpm-workspace.yaml",".npmrc","astro.config.mjs","tsconfig.json"].includes(path)||path.startsWith("src/")||path.startsWith("public/");return [".fvmrc",".metadata","analysis_options.yaml","pubspec.yaml","pubspec.lock"].includes(path)||path.startsWith("lib/")||path.startsWith("web/");}
function id(value:string):boolean{return /^[a-z0-9_-]{22,128}$/.test(value);}function timestamp(value:string):boolean{return /^[0-9]{4}-[0-9]{2}-[0-9]{2}T[0-9]{2}:[0-9]{2}:[0-9]{2}\.[0-9]{3}Z$/.test(value)&&Number.isFinite(Date.parse(value));}
