import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import { describe, it } from "node:test";

import { canonicalJsonDigest, canonicalManifestBytes, canonicalPath, manifestAggregateDigest } from "../../src/studio/compilation/canonicalManifest.js";
import { ExactCapabilityStore, compilationPlan, compilationPlanCommands, createArtifactVerificationLease, transitionCompilationJob, validateCapability, validateCompilationJob, validateCompilationPlan, validateCompilationResult } from "../../src/studio/compilation/contracts.js";
import { validateSourceManifest, verifyIndividuallyStreamedSource } from "../../src/studio/compilation/sourcePolicy.js";
import { artifactContract, validateArtifactContract, validateArtifactManifest, verifyArtifactByteStream } from "../../src/studio/compilation/artifactPolicy.js";
import { PILOT_COMPILATION_BUDGET, CompilationBudgetLedger, validateCompilationBudget, validateLedgerReservation, validateProviderUsageReceipt, type LedgerReservationV1, type ProviderUsageReceiptV1 } from "../../src/studio/compilation/budgetLedger.js";

/* eslint-disable @typescript-eslint/no-unnecessary-condition -- hostile array-state assertions intentionally retain runtime guards */

const id="abcdefghijklmnopqrstuv", id2="bcdefghijklmnopqrstuvw", id3="cdefghijklmnopqrstuvwx", hex="a".repeat(64), now=new Date("2026-08-16T12:00:00.000Z");
const stamp="2026-08-16T10:00:00.000Z";

describe("Linux compilation A1 normative contracts",()=>{
  it("loads every canonical fixture byte-for-byte and validates it",async()=>{
    for(const name of ["artifact-contract-astro-web-v1.json","artifact-contract-flutter-web-v1.json"]){const raw=await readFile(new URL("../fixtures/linux-compilation/contracts/"+name,import.meta.url));const parsed=JSON.parse(raw.toString("utf8"));assert.deepEqual(Buffer.from(canonicalManifestBytes(parsed)),raw);validateArtifactContract(parsed);}
    for(const name of ["artifact-manifest-astro-web-valid-v1.json","artifact-manifest-flutter-web-valid-v1.json"]){const raw=await readFile(new URL("../fixtures/linux-compilation/contracts/"+name,import.meta.url));const parsed=JSON.parse(raw.toString("utf8"));assert.deepEqual(Buffer.from(canonicalManifestBytes(parsed)),raw);validateArtifactManifest(parsed,artifactContract(parsed.target));}
  });
  it("canonicalizes JSON/LF, NFC, lowercase collisions and UTF-8 ordering",()=>{
    assert.equal(new TextDecoder().decode(canonicalManifestBytes({a:1,b:"é"})),'{"a":1,"b":"é"}\n');
    for(const path of ["/x","C:/x","a\\b","a/../b","a//b","a\u0000b","a/","cafe\u0301.txt"])assert.throws(()=>canonicalPath(path));
    const entries=[entry("a.txt",1),entry("b.txt",2)];assert.match(manifestAggregateDigest(entries),/^[a-f0-9]{64}$/);assert.throws(()=>manifestAggregateDigest([...entries].reverse()),/order/i);assert.throws(()=>manifestAggregateDigest([entry("A.txt",1),entry("a.txt",1)]),/collision/i);
  });
  it("uses fixed enum argv and the exhaustive state graph",()=>{
    assert.deepEqual(compilationPlanCommands("astro_web_v1"),[["pnpm","install","--offline","--frozen-lockfile","--ignore-scripts"],["pnpm","exec","astro","check"],["pnpm","exec","astro","build"]]);assert.deepEqual(compilationPlanCommands("flutter_web_v1"),[["flutter","pub","get","--offline","--enforce-lockfile"],["flutter","build","web","--release","--no-pub"]]);const plan=compilationPlan("astro_web_v1",id,id);assert.deepEqual(validateCompilationPlan(plan),plan);assert.throws(()=>validateCompilationPlan({...plan,extra:true}));assert.throws(()=>compilationPlan("shell" as never,id,id));
    const graph={planned:["admitted","failed","quarantined","revoked"],admitted:["running","failed","quarantined","revoked"],running:["retrieving","failed","quarantined","revoked"],retrieving:["verified","failed","quarantined","revoked"],verified:["released","quarantined","revoked"],failed:["quarantined","revoked"],quarantined:["revoked"],released:["revoked"],revoked:[]} as const;
    for(const [from,allowed] of Object.entries(graph))for(const to of Object.keys(graph)){if((allowed as readonly string[]).includes(to))assert.equal(transitionCompilationJob(from as never,to as never),to);else assert.throws(()=>transitionCompilationJob(from as never,to as never));}
  });
  it("validates all job fields, correlations, distinct phase digests and unknown keys",()=>{const job=validJob();assert.deepEqual(validateCompilationJob(job),job);assert.throws(()=>validateCompilationJob({...job,extra:true}));assert.throws(()=>validateCompilationJob({...job,executionClass:"linux_flutter"}));assert.throws(()=>validateCompilationJob({...job,state:"failed",reason:null}));assert.throws(()=>validateCompilationJob({...job,admissionCapabilityDigest:"x"}));assert.throws(()=>validateCompilationJob({...job,admissionCapabilityDigest:hex,sourceIngressCapabilityDigest:hex}));});
  it("enforces exact success, failed, quarantined and revoked result evidence matrices",()=>{const success=result({state:"verified",reason:null,artifactManifestDigest:hex,artifactAggregateDigest:hex,workerEvidenceDigest:hex});validateCompilationResult(success);const failure=result({state:"failed",reason:"executionFailed",artifactManifestDigest:null,artifactAggregateDigest:null,workerEvidenceDigest:null});validateCompilationResult(failure);validateCompilationResult(result({state:"quarantined",reason:"cleanupUncertain",artifactManifestDigest:hex,artifactAggregateDigest:hex,workerEvidenceDigest:hex}));validateCompilationResult(result({state:"revoked",reason:"revoked",artifactManifestDigest:null,artifactAggregateDigest:null,workerEvidenceDigest:null}));assert.throws(()=>validateCompilationResult(result({state:"failed",reason:"executionFailed",artifactManifestDigest:hex,artifactAggregateDigest:hex,workerEvidenceDigest:hex})));assert.throws(()=>validateCompilationResult(result({state:"revoked",reason:"revoked",artifactManifestDigest:hex,artifactAggregateDigest:hex,workerEvidenceDigest:hex})));assert.throws(()=>validateCompilationResult(result({state:"quarantined",reason:"cleanupUncertain",artifactManifestDigest:hex,artifactAggregateDigest:null,workerEvidenceDigest:hex})));assert.throws(()=>validateCompilationResult({...success,resultDigest:hex}));assert.throws(()=>validateCompilationResult({...failure,reason:null}));});
  it("enforces source allowlists, partial/digest drift and every source N/N+1",()=>{
    const ordinary=source([sourceEntry("src/index.ts","ordinary",2097152)]);validateSourceManifest(ordinary);assert.throws(()=>validateSourceManifest(source([sourceEntry("src/index.ts","ordinary",2097153)])),/limit/i);
    validateSourceManifest(source([sourceEntry("public/asset.bin","asset",16777216)]));assert.throws(()=>validateSourceManifest(source([sourceEntry("public/asset.bin","asset",16777217)])),/limit/i);
    const many=Array.from({length:4096},(_,index)=>sourceEntry("src/f"+String(index).padStart(4,"0")+".ts","ordinary",0));validateSourceManifest(source(many));assert.throws(()=>validateSourceManifest(source([...many,sourceEntry("src/z.ts","ordinary",0)])));
    const total=Array.from({length:32},(_,index)=>sourceEntry("src/t"+String(index).padStart(2,"0")+".ts","ordinary",2097152));validateSourceManifest(source(total));assert.throws(()=>validateSourceManifest(source([...total,sourceEntry("src/z.ts","ordinary",1)])),/limit/i);
    assert.throws(()=>validateSourceManifest(source([sourceEntry("secret.env","ordinary",1)])));assert.throws(()=>validateSourceManifest({...ordinary,sourceAggregateDigest:hex}));
  });
  it("seals only one-link regular source streams and rejects partial/special/TOCTOU",()=>{const bytes=new TextEncoder().encode("ok"),fileDigest="2689367b205c16ce32ed4200942b8b8b1e262dfc70d9bc9fbc77c49699a4f1df",entryValue={path:"src/x.ts",kind:"ordinary" as const,sizeBytes:2,fileDigest},observation={identity:"file-1",kind:"regular" as const,linkCount:1 as const,mode:"0644",sizeBytes:2,fileDigest};assert.equal(verifyIndividuallyStreamedSource(entryValue,observation,[bytes],observation),fileDigest);assert.throws(()=>verifyIndividuallyStreamedSource(entryValue,observation,[bytes.subarray(0,1)],observation));for(const changed of [{identity:"file-2"},{mode:"0755"},{kind:"symlink"},{kind:"fifo"},{linkCount:2}])assert.throws(()=>verifyIndividuallyStreamedSource(entryValue,observation,[bytes],{...observation,...changed}),/changed/i);});
  it("verifies artifact bytes rather than provider claims and rejects special/link/TOCTOU",()=>{const bytes=new TextEncoder().encode("ok"),fileDigest="2689367b205c16ce32ed4200942b8b8b1e262dfc70d9bc9fbc77c49699a4f1df",entryValue={path:"index.html",mediaType:"text/html",mode:"0644" as const,sizeBytes:2,fileDigest},observation={identity:"artifact-1",kind:"regular" as const,linkCount:1 as const,mode:"0644" as const,sizeBytes:2,fileDigest};assert.equal(verifyArtifactByteStream(entryValue,observation,[bytes],observation),fileDigest);assert.throws(()=>verifyArtifactByteStream(entryValue,observation,[new TextEncoder().encode("no")],observation),/changed/i);for(const changed of [{identity:"artifact-2"},{mode:"0444"},{kind:"device"},{linkCount:2}])assert.throws(()=>verifyArtifactByteStream(entryValue,observation,[bytes],{...observation,...changed}),/changed/i);});
  it("freezes exact artifact maps, roots, entrypoints, modes and limits",()=>{
    const astro=artifactContract("astro_web"),flutter=artifactContract("flutter_web");assert.deepEqual(validateArtifactContract(astro),astro);assert.throws(()=>validateArtifactContract({...astro,extra:true}));assert.equal(astro.root,"dist");assert.deepEqual(flutter.requiredEntrypoints,["flutter.js","flutter_bootstrap.js","index.html","manifest.json","version.json"]);
    const valid=artifact([artifactEntry("index.html","text/html","0644",16777216)],astro);validateArtifactManifest(valid,astro);
    for(const changed of [{path:"x.map",mediaType:"text/plain"},{path:"x.exe",mediaType:"application/octet-stream"},{path:"x.js",mediaType:"text/css"},{path:"x.js",mediaType:"text/javascript",mode:"0755"}])assert.throws(()=>validateArtifactManifest(artifact([{...artifactEntry("index.html","text/html"),...changed} as never],astro),astro));
    assert.throws(()=>validateArtifactManifest(artifact([artifactEntry("assets/x.bin","application/octet-stream")],flutter),flutter),/entrypoint/i);assert.throws(()=>validateArtifactManifest(artifact([artifactEntry("index.html","text/html","0644",16777217)],astro),astro));
    const many=[artifactEntry("index.html","text/html"),...Array.from({length:4095},(_,index)=>artifactEntry("x/f"+String(index).padStart(4,"0")+".js","text/javascript"))];validateArtifactManifest(artifact(many,astro),astro);assert.throws(()=>validateArtifactManifest(artifact([...many,artifactEntry("z.js","text/javascript")],astro),astro));
    const total=[artifactEntry("index.html","text/html","0644",16777216),...Array.from({length:7},(_,index)=>artifactEntry("x/t"+String(index)+".js","text/javascript","0644",16777216))];validateArtifactManifest(artifact(total,astro),astro);assert.throws(()=>validateArtifactManifest(artifact([...total,artifactEntry("x/z.js","text/javascript")],astro),astro),/limit/i);
  });
  it("rejects capability unknown keys, cross-phase use, TTL N+1 and replay",()=>{
    const store=new ExactCapabilityStore(),grant=store.issueAdmission(admission());validateCapability(grant);assert.throws(()=>validateCapability({...grant,extra:true}));assert.throws(()=>store.consume(grant.capabilityId,new Date("invalid"),{jobId:id,tenantId:id,projectId:id,target:"astro_web",phase:"admission",routeRequirementDigest:hex,budgetDigest:hex}),/invalid/i);assert.throws(()=>store.consume(grant.capabilityId,new Date("2026-08-16T10:01:00.000Z"),{jobId:id,tenantId:id,projectId:id,target:"astro_web",phase:"execution",routeRequirementDigest:hex}),/invalid/i);
    assert.throws(()=>new ExactCapabilityStore().issueAdmission({...admission(),capabilityId:id2,expiresAt:"2026-08-16T10:05:00.001Z"}));
    const freshStore=new ExactCapabilityStore(),fresh=freshStore.issueAdmission({...admission(),capabilityId:id3});const scope={jobId:id,tenantId:id,projectId:id,target:"astro_web" as const,phase:"admission" as const,routeRequirementDigest:hex,budgetDigest:hex};freshStore.consume(fresh.capabilityId,new Date("2026-08-16T10:05:00.000Z"),scope);assert.throws(()=>freshStore.consume(fresh.capabilityId,new Date("2026-08-16T10:05:00.000Z"),scope),/replayed/i);
  });
  it("materializes and validates every bearer phase schema independently",()=>{const store=new ExactCapabilityStore();const sourceGrant=store.issueSourceIngress({schemaVersion:"source-ingress-capability-v1",capabilityId:id,jobId:id,tenantId:id,projectId:id,target:"astro_web",routeRequirementDigest:hex,sourceManifestDigest:hex,sourceAggregateDigest:hex,workerEvidenceDigest:hex,phase:"source_ingress",issuedAt:stamp,expiresAt:"2026-08-16T10:05:00.000Z"});const executionGrant=store.issueExecution({schemaVersion:"execution-capability-v1",capabilityId:id2,jobId:id,tenantId:id,projectId:id,target:"astro_web",routeRequirementDigest:hex,sourceAggregateDigest:hex,workerEvidenceDigest:hex,planDigest:hex,artifactContractDigest:hex,phase:"execution",issuedAt:stamp,expiresAt:"2026-08-16T10:05:00.000Z"});const egressGrant=store.issueArtifactEgress({schemaVersion:"artifact-egress-capability-v1",capabilityId:id3,jobId:id,tenantId:id,projectId:id,target:"astro_web",routeRequirementDigest:hex,artifactManifestDigest:hex,artifactAggregateDigest:hex,privateBrokerObjectDigest:hex,cleanupEvidenceDigest:hex,phase:"artifact_egress",issuedAt:stamp,expiresAt:"2026-08-16T10:05:00.000Z"});for(const grant of [sourceGrant,executionGrant,egressGrant])assert.deepEqual(validateCapability(grant),grant);assert.notEqual(sourceGrant.capabilityDigest,executionGrant.capabilityDigest);assert.notEqual(executionGrant.capabilityDigest,egressGrant.capabilityDigest);});
  it("atomically rejects stale evidence for every bearer phase",()=>{for(const phase of ["admission","source_ingress","execution","artifact_egress"] as const){const store=new ExactCapabilityStore();const grant=phase==="admission"?store.issueAdmission(admission()):phase==="source_ingress"?store.issueSourceIngress({schemaVersion:"source-ingress-capability-v1",capabilityId:id,jobId:id,tenantId:id,projectId:id,target:"astro_web",routeRequirementDigest:hex,sourceManifestDigest:hex,sourceAggregateDigest:hex,workerEvidenceDigest:hex,phase,issuedAt:stamp,expiresAt:"2026-08-16T10:05:00.000Z"}):phase==="execution"?store.issueExecution({schemaVersion:"execution-capability-v1",capabilityId:id,jobId:id,tenantId:id,projectId:id,target:"astro_web",routeRequirementDigest:hex,sourceAggregateDigest:hex,workerEvidenceDigest:hex,planDigest:hex,artifactContractDigest:hex,phase,issuedAt:stamp,expiresAt:"2026-08-16T10:05:00.000Z"}):store.issueArtifactEgress({schemaVersion:"artifact-egress-capability-v1",capabilityId:id,jobId:id,tenantId:id,projectId:id,target:"astro_web",routeRequirementDigest:hex,artifactManifestDigest:hex,artifactAggregateDigest:hex,privateBrokerObjectDigest:hex,cleanupEvidenceDigest:hex,phase,issuedAt:stamp,expiresAt:"2026-08-16T10:05:00.000Z"});assert.throws(()=>store.consume(grant.capabilityId,new Date("2026-08-16T10:01:00.000Z"),{jobId:id,tenantId:id,projectId:id,target:"astro_web",phase,routeRequirementDigest:hex,budgetDigest:"b".repeat(64),sourceManifestDigest:"b".repeat(64),sourceAggregateDigest:"b".repeat(64),workerEvidenceDigest:"b".repeat(64),planDigest:"b".repeat(64),artifactContractDigest:"b".repeat(64),artifactManifestDigest:"b".repeat(64),artifactAggregateDigest:"b".repeat(64),privateBrokerObjectDigest:"b".repeat(64),cleanupEvidenceDigest:"b".repeat(64)}),/invalid/i);}});
  it("rejects invalid or non-positive lease dates",()=>{const base={leaseId:id,jobId:id,tenantId:id,projectId:id,target:"astro_web" as const,routeRequirementDigest:hex,artifactContractDigest:hex,providerResourceIdDigest:hex,workerEvidenceDigest:hex};assert.throws(()=>createArtifactVerificationLease({...base,issuedAt:"not-date",expiresAt:"2026-08-16T10:05:00.000Z"}));assert.throws(()=>createArtifactVerificationLease({...base,issuedAt:stamp,expiresAt:stamp}));});
  it("keeps verifier lease internal, one-use, non-serializable and unchanged on invalid time",()=>{const lease=createArtifactVerificationLease({leaseId:id,jobId:id,tenantId:id,projectId:id,target:"astro_web",routeRequirementDigest:hex,artifactContractDigest:hex,providerResourceIdDigest:hex,workerEvidenceDigest:hex,issuedAt:stamp,expiresAt:"2026-08-16T10:05:00.000Z"});assert.throws(()=>JSON.stringify(lease));assert.throws(()=>lease.consume(new Date("invalid")),/invalid/i);assert.equal(lease.state,"issued");lease.consume(new Date("2026-08-16T10:01:00.000Z"));assert.throws(()=>lease.consume(new Date("2026-08-16T10:02:00.000Z")));});
  it("validates the literal immutable budget and every numeric N/N+1",()=>{assert.equal(validateCompilationBudget(PILOT_COMPILATION_BUDGET),PILOT_COMPILATION_BUDGET);for(const [key,value] of Object.entries(PILOT_COMPILATION_BUDGET)){if(typeof value==="number"){assert.doesNotThrow(()=>validateCompilationBudget({...PILOT_COMPILATION_BUDGET,[key]:value}));assert.throws(()=>validateCompilationBudget({...PILOT_COMPILATION_BUDGET,[key]:value+1}));}}assert.throws(()=>validateCompilationBudget({...PILOT_COMPILATION_BUDGET,extra:0}));});
  it("provides CAS, restart, concurrency and idempotent receipt settlement",()=>{
    const ledger=new CompilationBudgetLedger(now),r1=reservation(id,id,id,id,"1.000000"),s1=ledger.reserve(r1,0,now);assert.equal(s1.revision,1);assert.throws(()=>ledger.reserve(reservation(id2,id2,id,id2,"1.000000"),1,now),/unavailable/i);const r2=reservation(id2,id2,id2,id2,"1.000000"),s2=ledger.reserve(r2,1,now);assert.equal(s2.ledger.reservedEur,"2.000000");assert.throws(()=>ledger.reserve(reservation(id3,id3,id3,id3,"1.000000"),2,now),/unavailable/i);assert.throws(()=>ledger.observeCreate(id,1,now),/revision/i);
    const observed=ledger.observeCreate(id,2,now),receipt=usageReceipt(r1,"1.000000","0.500000","0.550000"),settled=ledger.settle(receipt,observed.revision,true,new Date("2026-08-16T12:01:00.000Z"));assert.equal(settled.ledger.chargedEur,"0.550000");const same=ledger.settle(receipt,settled.revision,true,new Date("2026-08-16T12:02:00.000Z"));assert.equal(same.revision,settled.revision);const released=ledger.release(id,same.revision,new Date("2026-08-16T12:03:00.000Z"));assert.throws(()=>ledger.retain(id,released.revision,now),/unavailable/i);const restored=CompilationBudgetLedger.restore(released,released.ledger.ledgerDigest);assert.deepEqual(restored.snapshot(),released);assert.throws(()=>restored.reserve(reservation(id3,id,id3,id3,"0.100000",1),released.revision,now),/unavailable/i);
  });
  it("retains reservations indefinitely on uncertain cleanup after one final receipt and survives restart",()=>{const ledger=new CompilationBudgetLedger(now),r=reservation(id,id,id,id,"1.000000"),reserved=ledger.reserve(r,0,now),receipt=usageReceipt(r,"1.000000","0.500000","0.550000"),retained=ledger.settle(receipt,reserved.revision,false,new Date("2026-08-16T12:01:00.000Z"));assert.equal(retained.ledger.uncertain,true);assert.equal(retained.ledger.expiresAt,null);assert.equal(retained.reservations[0]?.state,"retained");assert.deepEqual(CompilationBudgetLedger.restore(retained,retained.ledger.ledgerDigest).snapshot(),retained);});
  it("accepts one final receipt lifetime and atomically rejects a different or concurrent second final",()=>{const ledger=new CompilationBudgetLedger(now),r=reservation(id,id,id,id,"1.000000"),reserved=ledger.reserve(r,0,now),created=ledger.observeCreate(id,reserved.revision,now),first=usageReceipt(r,"1.000000","0.500000","0.550000"),settled=ledger.settle(first,created.revision,true,new Date("2026-08-16T12:01:00.000Z")),released=ledger.release(id,settled.revision,new Date("2026-08-16T12:02:00.000Z")),second=redigestReceipt({...first,receiptId:id2,providerReceiptDigest:"b".repeat(64),observedAt:"2026-08-16T12:02:30.000Z"});const before=JSON.stringify(released);assert.throws(()=>ledger.settle(second,released.revision,true,new Date("2026-08-16T12:03:00.000Z")),/unavailable/i);assert.equal(JSON.stringify(ledger.snapshot()),before);const concurrent=new CompilationBudgetLedger(now),reserved2=concurrent.reserve(r,0,now),created2=concurrent.observeCreate(id,reserved2.revision,now);concurrent.settle(first,created2.revision,true,new Date("2026-08-16T12:01:00.000Z"));const won=JSON.stringify(concurrent.snapshot());assert.throws(()=>concurrent.settle(second,created2.revision,true,new Date("2026-08-16T12:03:00.000Z")),/revision/i);assert.equal(JSON.stringify(concurrent.snapshot()),won);assert.throws(()=>redigestReceipt({...first,final:false}),/invalid/i);});
  it("atomically transfers an uncreated attempt zero reservation to one restart-safe retry",()=>{const ledger=new CompilationBudgetLedger(now),attempt0=reservation(id,id,id,id,"1.000000"),reserved=ledger.reserve(attempt0,0,now),attempt1=reservation(id2,id,id,id,"1.000000",1),retried=ledger.retryBeforeCreate(id,attempt1,"b".repeat(64),reserved.revision,new Date("2026-08-16T12:01:00.000Z"));assert.equal(retried.ledger.reservedEur,"1.000000");assert.deepEqual(retried.liveReservationIds,[id2]);assert.equal(retried.reservations.find((item)=>item.reservationId===id)?.state,"retired");assert.equal(retried.reservations.find((item)=>item.reservationId===id)?.retryEvidenceDigest,"b".repeat(64));const restored=CompilationBudgetLedger.restore(retried,retried.ledger.ledgerDigest);assert.deepEqual(restored.snapshot(),retried);const before=JSON.stringify(retried);assert.throws(()=>ledger.retryBeforeCreate(id,attempt1,"b".repeat(64),retried.revision,new Date("2026-08-16T12:02:00.000Z")),/unavailable/i);assert.equal(JSON.stringify(ledger.snapshot()),before);const concurrent=new CompilationBudgetLedger(now),first=concurrent.reserve(attempt0,0,now);concurrent.retryBeforeCreate(id,attempt1,"b".repeat(64),first.revision,new Date("2026-08-16T12:01:00.000Z"));assert.throws(()=>concurrent.retryBeforeCreate(id,attempt1,"b".repeat(64),first.revision,new Date("2026-08-16T12:01:00.000Z")),/revision/i);const createdLedger=new CompilationBudgetLedger(now),createdReservation=createdLedger.reserve(attempt0,0,now),created=createdLedger.observeCreate(id,createdReservation.revision,now),createdBefore=JSON.stringify(created);assert.throws(()=>createdLedger.retryBeforeCreate(id,attempt1,"b".repeat(64),created.revision,new Date("2026-08-16T12:01:00.000Z")),/unavailable/i);assert.equal(JSON.stringify(createdLedger.snapshot()),createdBefore);});
  it("reconciles uncertain cleanup once with exact resource evidence and survives restart",()=>{const ledger=new CompilationBudgetLedger(now),r=reservation(id,id,id,id,"1.000000"),reserved=ledger.reserve(r,0,now),created=ledger.observeCreate(id,reserved.revision,now),receipt=usageReceipt(r,"1.000000","0.500000","0.550000"),retained=ledger.settle(receipt,created.revision,false,new Date("2026-08-16T12:01:00.000Z")),cleanupDigest="b".repeat(64),beforeBad=JSON.stringify(retained);assert.throws(()=>ledger.reconcileCleanup(id,"c".repeat(64),cleanupDigest,"2026-08-16T12:02:00.000Z",retained.revision,new Date("2026-08-16T12:02:00.000Z")),/unavailable/i);assert.throws(()=>ledger.reconcileCleanup(id,hex,cleanupDigest,"2026-08-16T12:02:00.001Z",retained.revision,new Date("2026-08-16T12:02:00.000Z")),/unavailable/i);assert.equal(JSON.stringify(ledger.snapshot()),beforeBad);const reconciled=ledger.reconcileCleanup(id,hex,cleanupDigest,"2026-08-16T12:02:00.000Z",retained.revision,new Date("2026-08-16T12:02:00.000Z"));assert.equal(reconciled.reservations[0]?.state,"settled");assert.equal(reconciled.reservations[0]?.cleanupEvidenceDigest,cleanupDigest);assert.equal(reconciled.ledger.uncertain,false);assert.deepEqual(reconciled.liveReservationIds,[]);assert.deepEqual(reconciled.ledger.quarantinedJobIds,[]);const restored=CompilationBudgetLedger.restore(reconciled,reconciled.ledger.ledgerDigest);assert.deepEqual(restored.snapshot(),reconciled);assert.equal(ledger.reconcileCleanup(id,hex,cleanupDigest,"2026-08-16T12:02:00.000Z",reconciled.revision,new Date("2026-08-16T12:03:00.000Z")).revision,reconciled.revision);for(const [resource,evidence] of [["c".repeat(64),cleanupDigest],[hex,"c".repeat(64)]] as const){const before=JSON.stringify(ledger.snapshot());assert.throws(()=>ledger.reconcileCleanup(id,resource,evidence,"2026-08-16T12:02:00.000Z",reconciled.revision,new Date("2026-08-16T12:03:00.000Z")),/unavailable/i);assert.equal(JSON.stringify(ledger.snapshot()),before);}});
  it("leaves byte-identical ledger snapshots after invalid or non-monotonic time in every method",()=>{const invalid=new Date("invalid"),ledger=new CompilationBudgetLedger(now),r=reservation(id,id,id,id,"1.000000");const unchanged=(action:()=>unknown)=>{const before=JSON.stringify(ledger.snapshot());assert.throws(action,/unavailable/i);assert.equal(JSON.stringify(ledger.snapshot()),before);};unchanged(()=>ledger.reserve(r,0,invalid));const reserved=ledger.reserve(r,0,now);unchanged(()=>ledger.observeCreate(id,reserved.revision,invalid));unchanged(()=>ledger.retain(id,reserved.revision,invalid));unchanged(()=>ledger.release(id,reserved.revision,invalid));unchanged(()=>ledger.settle(usageReceipt(r,"1.000000","0.500000","0.550000"),reserved.revision,true,invalid));unchanged(()=>ledger.observeCreate(id,reserved.revision,new Date("2026-08-16T11:59:59.999Z")));});
  it("rejects forged indexes and rewritten nested records against durable anchor",()=>{const ledger=new CompilationBudgetLedger(now),snapshot=ledger.reserve(reservation(id,id,id,id,"1.000000"),0,now),anchor=snapshot.ledger.ledgerDigest;assert.throws(()=>CompilationBudgetLedger.restore({...snapshot,liveReservationIds:[]},anchor));assert.throws(()=>CompilationBudgetLedger.restore({...snapshot,createObservedJobIds:[id]},anchor));const original=snapshot.reservations[0];if(original===undefined)assert.fail("reservation fixture");const forgedReservation={...original,reservedEur:"0.500000"};assert.throws(()=>CompilationBudgetLedger.restore({...snapshot,reservations:[forgedReservation]},anchor));const observed=ledger.observeCreate(id,snapshot.revision,now);assert.throws(()=>CompilationBudgetLedger.restore({...observed,createObservedJobIds:[]},observed.ledger.ledgerDigest));const restored=CompilationBudgetLedger.restore(observed,observed.ledger.ledgerDigest);assert.throws(()=>restored.reserve(reservation(id2,id,id2,id2,"1.000000",1),observed.revision,now),/unavailable/i);});
  it("enforces every receipt resource/log/transfer boundary, identity and freshness",()=>{const r=reservation(id,id,id,id,"1.000000"),base=usageReceipt(r,"1.000000","0.500000","0.550000");const boundaries={controlCallCount:32,durationMs:600000,activeCpuMs:2400000,peakMemoryBytes:8589934592,provisionedMemoryByteMs:5153960755200000,diskBytes:21474836480,processCount:256,stdoutBytes:1048576,stderrBytes:1048576,ingressBytes:67108864,sourceFileCount:4096,artifactFileCount:4096,vcrImageBytes:16106127360,vcrStorageByteMs:6442450944000000,egressBytes:134217728};for(const [key,value] of Object.entries(boundaries)){const core={...base,...(key==="activeCpuMs"||key==="provisionedMemoryByteMs"?{durationMs:600000}:{}),[key]:value};assert.doesNotThrow(()=>redigestReceipt(core));assert.throws(()=>redigestReceipt({...core,[key]:value+1}));}const ledger=new CompilationBudgetLedger(now),reserved=ledger.reserve(r,0,now),wrong=redigestReceipt({...base,jobId:id2});assert.throws(()=>ledger.settle(wrong,reserved.revision,true,now));for(const observedAt of ["2026-08-16T12:00:00.001Z","2026-08-16T11:44:59.999Z","2026-08-15T09:59:59.999Z"])assert.throws(()=>ledger.settle(redigestReceipt({...base,observedAt}),reserved.revision,true,now));});
});

function entry(path:string,sizeBytes:number){return{path,sizeBytes,fileDigest:hex};}
function sourceEntry(path:string,kind:"ordinary"|"asset",sizeBytes=1){return{path,kind,sizeBytes,fileDigest:hex};}
function source(entries:readonly ReturnType<typeof sourceEntry>[]){const totalBytes=entries.reduce((sum,item)=>sum+item.sizeBytes,0);return{schemaVersion:"compilation-source-manifest-v1" as const,jobId:id,tenantId:id,projectId:id,target:"astro_web" as const,sourceRevision:"abc1234",entries,fileCount:entries.length,totalBytes,sourceAggregateDigest:manifestAggregateDigest(entries),createdAt:stamp};}
function artifactEntry(path:string,mediaType:string,mode:"0444"|"0644"="0644",sizeBytes=1){return{path,mediaType,mode,sizeBytes,fileDigest:hex};}
function artifact(entries:readonly ReturnType<typeof artifactEntry>[],contract:ReturnType<typeof artifactContract>){const sorted=[...entries].sort((a,b)=>Buffer.compare(Buffer.from(a.path),Buffer.from(b.path)));return{schemaVersion:"compilation-artifact-manifest-v1" as const,jobId:id,tenantId:id,projectId:id,target:contract.target,sourceAggregateDigest:hex,toolchainDigest:hex,imageDigest:hex,artifactContractDigest:contract.contractDigest,entries:sorted,fileCount:sorted.length,totalBytes:sorted.reduce((sum,item)=>sum+item.sizeBytes,0),artifactAggregateDigest:manifestAggregateDigest(sorted),createdAt:stamp};}
function validJob(){return{schemaVersion:"compilation-job-v1",jobId:id,tenantId:id,projectId:id,requestedTarget:"astro_web",sourceRevision:"abc",sourceManifestDigest:hex,sourceAggregateDigest:hex,routeRequirementDigest:hex,executionClass:"linux_node",toolchainProfile:"astro_static",toolchainDigest:hex,imageDigest:hex,policyDigest:hex,artifactContractDigest:hex,budgetDigest:hex,admissionCapabilityDigest:null,sourceIngressCapabilityDigest:null,executionCapabilityDigest:null,artifactVerificationLeaseDigest:null,artifactEgressCapabilityDigest:null,state:"planned",reason:null,createdAt:stamp,updatedAt:stamp,expiresAt:"2026-08-16T10:10:00.000Z"};}
function result(overrides:Record<string,unknown>){const core={schemaVersion:"compilation-result-v1",jobId:id,state:"verified",reason:null,sourceAggregateDigest:hex,artifactManifestDigest:hex,artifactAggregateDigest:hex,workerEvidenceDigest:hex,receiptDigest:null,stdoutDigest:null,stderrDigest:null,startedAt:stamp,finishedAt:"2026-08-16T10:01:00.000Z",...overrides};return{...core,resultDigest:canonicalJsonDigest(core)};}
function admission(){return{schemaVersion:"admission-capability-v1" as const,capabilityId:id,jobId:id,tenantId:id,projectId:id,target:"astro_web" as const,routeRequirementDigest:hex,budgetDigest:hex,phase:"admission" as const,issuedAt:stamp,expiresAt:"2026-08-16T10:05:00.000Z"};}
function reservation(reservationId:string,jobId:string,tenantId:string,projectId:string,reservedEur:string,attempt:0|1=0):LedgerReservationV1{return validateLedgerReservation({schemaVersion:"ledger-reservation-v1",reservationId,chantierId:"shipglows-linux-compilation-workers",jobId,tenantId,projectId,attempt,dimensions:PILOT_COMPILATION_BUDGET,reservedEur,ecbRateDate:"2026-08-16",ecbEurUsdRate:"2.000000",ecbEvidenceDigest:hex,contingencyBasisPoints:1000,state:"reserved",retryEvidenceDigest:null,cleanupEvidenceDigest:null,createdAt:stamp,updatedAt:stamp,expiresAt:null});}
function usageReceipt(reservationValue:LedgerReservationV1,rawUsd:string,convertedEur:string,contingencyEur:string,final=true):ProviderUsageReceiptV1{const core={schemaVersion:"provider-usage-receipt-v1" as const,receiptId:id3,provider:"vercel_sandbox" as const,providerReceiptDigest:hex,reservationId:reservationValue.reservationId,jobId:reservationValue.jobId,providerResourceIdDigest:hex,activeCpuMs:1,provisionedMemoryByteMs:1,creationCount:1 as const,controlCallCount:1,durationMs:1,peakMemoryBytes:1,diskBytes:1,processCount:1,stdoutBytes:1,stderrBytes:1,ingressBytes:1,sourceFileCount:1,artifactFileCount:1,vcrImageBytes:1,vcrStorageByteMs:1,snapshotStorageByteMs:0 as const,egressBytes:1,rawUsd,convertedEur,contingencyEur,observedAt:"2026-08-16T12:01:00.000Z",final};return validateProviderUsageReceipt({...core,receiptDigest:canonicalJsonDigest(core)});}
function redigestReceipt(value:Record<string,unknown>):ProviderUsageReceiptV1{const core=Object.fromEntries(Object.entries(value).filter(([key])=>key!=="receiptDigest"));return validateProviderUsageReceipt({...core,receiptDigest:canonicalJsonDigest(core)} as unknown as ProviderUsageReceiptV1);}
